---
title: "stephanie_post"
description: |
  A short description of the post.
author:
  - name: Nora Jones
    url: https://example.com/norajones
date: 05-08-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include= TRUE}
knitr::opts_chunk$set(echo = FALSE)



```

To create a new page on your blog 
`distill::create_post("post_title")`


To tackle the outline: 

1) Set up a working directory complete with an Rproject and subfolders - Brock
 
2) Subsetting data and outputting basic descriptives - Akhila & Stephanie 
  - Custom functions for means and standard deviation
  - Rename Akhila's first post - Dataset Descriptives Tutorial
  - Idea: Subset by week (function to separate dates by incrememnts of 7), location, and country, to get average activity per week in each location.

3) Loop through regression/other stats models to extract plots - Joanna

4) Creating folders to export plots with meaningful paramters (e.g., names, plot dimensions) - Akhila & Stephanie 



Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

